"""
Django settings for projectname project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+vn$p(dyj2uwd%ow=4zkewm#2-2_m8&qczjiv+8ic7s&j3)zp5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['narwhaltutoring.up.railway.app',
                '127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['https://narwhaltutoring.up.railway.app']

# Application definition

INSTALLED_APPS = [
    'Narwhal_Tutoring',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

ROOT_URLCONF = 'projectname.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projectname.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:  
    # Parse the default DATABASE_URL environment variable from Railway
    db_from_env = dj_database_url.config(default=os.getenv('RAILWAY_DATABASE_URL'))

    # Update DATABASES with the parsed configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': db_from_env['HOST'],
            'PORT': db_from_env['PORT'],
            'NAME': db_from_env['NAME'],
            'USER': db_from_env['USER'],
            'PASSWORD': db_from_env['PASSWORD'],
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'Narwhal_Tutoring.User'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-au'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
 
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Stripe Stuff
#STRIPE_PUBLIC_KEY = 'pk_live_51OYnzrKCFeavPzHiXRW7BKPuDOO2ofyXoZqmZ1ZRgi876NsnbwfB3CNpDeBO1JrOkf0X36PQgmgVC5uc6CT08rfO002lfYvOiF'
#STRIPE_SECRET_KEY = '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'

STRIPE_PUBLIC_KEY = "pk_test_51OYnzrKCFeavPzHi41M0qvMHiUkyM0ZcQvwVznFWFv8hV0zsx6RWlsZvk9hjpZfPMWmrx5LYLJWb07qTU8HHVkUj00YXqzerfq"
STRIPE_SECRET_KEY = "sk_test_51OYnzrKCFeavPzHiSkKjAqU9MoI1P2H2KDnrlbs4Pz26fSTitBWAjAxqrXssAsxqmFkWxFFVkP8CL4ojCcT9cukp00ejZa7JLW"