# Generated by Django 4.2.3 on 2024-01-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='atar',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='tutors', to='Narwhal_Tutoring.subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='suburb',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
