# Generated by Django 4.2.3 on 2024-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0002_alter_user_atar_alter_user_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
