# Generated by Django 4.2.3 on 2024-01-23 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0005_alter_user_available_alter_user_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday_times', models.ManyToManyField(related_name='friday', to='Narwhal_Tutoring.timeslot')),
                ('monday_times', models.ManyToManyField(related_name='monday', to='Narwhal_Tutoring.timeslot')),
                ('saturday_times', models.ManyToManyField(related_name='saturday', to='Narwhal_Tutoring.timeslot')),
                ('sunday_times', models.ManyToManyField(related_name='sunday', to='Narwhal_Tutoring.timeslot')),
                ('thursday_times', models.ManyToManyField(related_name='thursday', to='Narwhal_Tutoring.timeslot')),
                ('tuesday_times', models.ManyToManyField(related_name='tuesday', to='Narwhal_Tutoring.timeslot')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
                ('wednesday_times', models.ManyToManyField(related_name='wednesday', to='Narwhal_Tutoring.timeslot')),
            ],
        ),
    ]
