# Generated by Django 4.2.3 on 2024-01-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0010_remove_user_location_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(default='ATAR', max_length=20),
            preserve_default=False,
        ),
    ]
