# Generated by Django 4.2.3 on 2024-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0012_alter_tutoravailability_tutor_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='group_id',
            field=models.CharField(max_length=255),
        ),
    ]
