# Generated by Django 4.2.3 on 2024-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0013_alter_availability_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='event_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
