# Generated by Django 4.2.3 on 2024-01-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0014_availability_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='day_of_week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
