# Generated by Django 4.2.3 on 2024-02-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0016_alter_availability_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorAvailability',
        ),
    ]
