# Generated by Django 4.2.3 on 2024-02-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0019_cart_alter_availability_id_alter_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='event_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='event_id',
            field=models.CharField(max_length=255),
        ),
    ]
